#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_CDFINGER_FP_TEE) += cdfinger_fp_tee/
obj-$(CONFIG_BETTERLIFE_FINGERPRINT) += betterlife_fp/
obj-$(CONFIG_BETTERLIFE_FINGERPRINT_TEE) += betterlife_fp_tee/
obj-$(CONFIG_CDFINGER_FP_REE) += cdfinger_fp_ree/